### ISSUE TITLE
GPU doesn't seem to work

### ISSUE THREAD

**Issue by ggeorgo** [vanities/GPU-Passthrough-Arch-Linux-to-Windows10#1]
I managed to complete the whole process, my 1080ti is visible inside the VM, I installed the Nvidia drivers, but still, under device manager, GPU has an exclamation mark and does not work.

The monitor that is connected to the GPU, is displaying some BIOS/POST info, and then freezes, while the VM runs in a small window with a Microsoft display adapter.

**Comment by AlmightyFrog** [comment]
Seems like it is not directly your issue, but I also had at the beginning issues getting my geforce working properly. Picture came out on my graphic card, but it would not switch to the nvidia driver cause of the usual "Error 43".

The solution which in the end helped me is to modify config like it is mentioned here - maybe that helps also you: https://passthroughpo.st/apply-error-43-workaround/
The "hidden state" part is what I didn't read from other instructions which made my ststem working in the end.

If you have multiple nvidia graphic cards in your PC, for testing just remove one.
