### ISSUE TITLE
VM halt instant after starting

### ISSUE THREAD

**Issue by D1Ck3n** [vanities/GPU-Passthrough-Arch-Linux-to-Windows10#2]
Hi, firt of all thanks for the instructions!

i followed your instructions exactly and the GPU i wanted to isolate (AMD Rx 480) could also be isolated, but when i try to start the VM with PCI passthrough the VM stops immediately and my second monitor on which the VM should be displayed stays black.

i hope you can help me

**Comment by vanities** [comment]
No problem!

Oh man, sorry it's been so long since I've checked these issues. I don't have an amdgpu hooked up to try this, so I'm not sure if I can help.
