### ISSUE TITLE
Will I be able to use the gpu while not using the VM?

### ISSUE THREAD

**Issue by DokStook** [vanities/GPU-Passthrough-Arch-Linux-to-Windows10#7]
Not an issue. Just a question. I have read other tutorials that state that I am not going to be able to use the gpu if the vm is not in use. Is this true if I follow this tutorial?

**Comment by vanities** [comment]
I believe all GPU passthrough techniques require the loss of the gpu on the host side. So yes, sorry!

**Comment by DokStook** [comment]
This is sad... Thanks anyway!

**Comment by DokStook** [comment]
> I believe all GPU passthrough techniques require the loss of the gpu on the host side. So yes, sorry!

I was thinking about this for a while: what if I add another user who is only used for virtualization?
